export const fakeData = [
  {
    id: 1,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+1",
    name: "Product 1",
    full_Name: "John Doe",
    price: "$100",
  },
  {
    id: 2,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+2",
    name: "Product 2",
    full_Name: "Jane Smith",
    price: "$150",
  },
  {
    id: 3,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+3",
    name: "Product 3",
    full_Name: "Michael Johnson",
    price: "$200",
  },
  {
    id: 4,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+4",
    name: "Product 4",
    full_Name: "Emily Davis",
    price: "$250",
  },
  {
    id: 5,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+5",
    name: "Product 5",
    full_Name: "David Wilson",
    price: "$300",
  },
  {
    id: 6,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+6",
    name: "Product 6",
    full_Name: "Sarah Brown",
    price: "$350",
  },
  {
    id: 7,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+7",
    name: "Product 7",
    full_Name: "Chris Lee",
    price: "$400",
  },
  {
    id: 8,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+8",
    name: "Product 8",
    full_Name: "Anna Scott",
    price: "$450",
  },
  {
    id: 9,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+9",
    name: "Product 9",
    full_Name: "Paul Green",
    price: "$500",
  },
  {
    id: 10,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+10",
    name: "Product 10",
    full_Name: "Lisa Black",
    price: "$550",
  },
  {
    id: 1,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+1",
    name: "Product 1",
    full_Name: "John Doe",
    price: "$100",
  },
  {
    id: 2,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+2",
    name: "Product 2",
    full_Name: "Jane Smith",
    price: "$150",
  },
  {
    id: 3,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+3",
    name: "Product 3",
    full_Name: "Michael Johnson",
    price: "$200",
  },
  {
    id: 4,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+4",
    name: "Product 4",
    full_Name: "Emily Davis",
    price: "$250",
  },
  {
    id: 5,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+5",
    name: "Product 5",
    full_Name: "David Wilson",
    price: "$300",
  },
  {
    id: 6,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+6",
    name: "Product 6",
    full_Name: "Sarah Brown",
    price: "$350",
  },
  {
    id: 7,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+7",
    name: "Product 7",
    full_Name: "Chris Lee",
    price: "$400",
  },
  {
    id: 8,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+8",
    name: "Product 8",
    full_Name: "Anna Scott",
    price: "$450",
  },
  {
    id: 9,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+9",
    name: "Product 9",
    full_Name: "Paul Green",
    price: "$500",
  },
  {
    id: 10,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+10",
    name: "Product 10",
    full_Name: "Lisa Black",
    price: "$550",
  },
  {
    id: 1,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+1",
    name: "Product 1",
    full_Name: "John Doe",
    price: "$100",
  },
  {
    id: 2,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+2",
    name: "Product 2",
    full_Name: "Jane Smith",
    price: "$150",
  },
  {
    id: 3,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+3",
    name: "Product 3",
    full_Name: "Michael Johnson",
    price: "$200",
  },
  {
    id: 4,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+4",
    name: "Product 4",
    full_Name: "Emily Davis",
    price: "$250",
  },
  {
    id: 5,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+5",
    name: "Product 5",
    full_Name: "David Wilson",
    price: "$300",
  },
  {
    id: 6,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+6",
    name: "Product 6",
    full_Name: "Sarah Brown",
    price: "$350",
  },
  {
    id: 7,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+7",
    name: "Product 7",
    full_Name: "Chris Lee",
    price: "$400",
  },
  {
    id: 8,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+8",
    name: "Product 8",
    full_Name: "Anna Scott",
    price: "$450",
  },
  {
    id: 9,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+9",
    name: "Product 9",
    full_Name: "Paul Green",
    price: "$500",
  },
  {
    id: 10,
    url_Image: "https://via.placeholder.com/300x200.png?text=Product+10",
    name: "Product 10",
    full_Name: "Lisa Black",
    price: "$550",
  }
];
